version: "3.8"
services:
  airflow:
    image: apache/airflow:2.9.3
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
      - ./configs:/opt/airflow/configs
    ports:
      - "8080:8080"
    command: standalone
